name: server-application-b

services:
  api-service2:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    deploy:
      replicas: 5
    networks:
      - internal-b

  caddy:
    image: caddy:latest
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.my-router2.rule=Host(`ex.mehularora.dev`)'
      - 'traefik.http.services.my-router2.loadbalancer.server.port=80'
      - 'traefik.http.routers.my-router2.entrypoints=websecure'
      - 'traefik.docker.network=project-b-network'
      - 'traefik.http.routers.my-router2.tls=true'
      - 'traefik.http.routers.my-router2.tls.certresolver=cert-resolver'
    networks:
      - project-b-network
      - internal-b

networks:
  internal-b:
    driver: bridge
  project-b-network:
    external: true
