services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    expose:
      - "5678"
    environment:
      - N8N_HOST=n8n.mehularora.dev
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://n8n.mehularora.dev/
    volumes:
      - n8n_data:/home/node/.n8n
    labels:
      - "traefik.enable=true"
      # Match your sub-domain
      - "traefik.http.routers.n8n-svc.rule=Host(`n8n.mehularora.dev`)"
      # Route traffic to n8n's internal port
      - "traefik.http.services.n8n-svc.loadbalancer.server.port=5678"
      # Enforce TLS and use your ACME resolver setup in your api-gateway configuration
      - "traefik.http.routers.n8n-svc.entrypoints=websecure"
      - "traefik.http.routers.n8n-svc.tls=true"
      - "traefik.http.routers.n8n-svc.tls.certresolver=cert-resolver"
      # Tell Traefik which network to reach this container on
      - "traefik.docker.network=traefik"
    networks:
      - traefik

volumes:
  n8n_data:

networks:
  traefik:
    external: true